# Generated by Django 3.2.6 on 2021-08-12 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_of_task', models.CharField(max_length=150, verbose_name='Задание')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
